spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:test;MODE=mysql;DATABASE_TO_UPPER=false
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      continue-on-error: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        transaction:
          interceptor: trace

server:
  port: 8100