spring:
  profiles:
    active: production

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /home/opc/logs/mybook.log
  logback:
    rollingpolicy:
      file-name-pattern: "/home/opc/logs/mybook.%d{yyyy-MM-dd}.%i.log"
      max-history: 10
      max-file-size: 100MB